#hdfs:
#  image: sequenceiq/hadoop-docker:2.4.1
#  command: /etc/bootstrap.sh -d -bash

#mazerunner:
#  image: kbastani/neo4j-graph-analytics:latest
#  links:
#   - hdfs

graphdb:
  build: .
  dockerfile: ./compose/graphdb/Dockerfile
  ports:
   - "7474:7474"
   - "1337:1337"
#  links:
#   - mazerunner
#   - hdfs

postgres:
    image: postgres:9.4
    env_file: .env
    expose:
        - "5432"

uwsgi:
    image: rwblair/cogat
    command: /code/compose/uwsgi/uwsgi.sh
    restart: always
    env_file: .env
    volumes:
        - .:/code
        - /var/www/static
    links:
        - postgres
        - graphdb

nginx:
    restart: always
    image: nginx
    volumes_from:
        - uwsgi
    volumes:
        - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./compose/nginx/uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
    links:
        - uwsgi
    ports:
        - "80:80"

import:
    build: .
    dockerfile: ./compose/import/Dockerfile
    command: /code/compose/import/entrypoint.sh
    env_file: .env
    volumes:
        - .:/code
    links:
        - nginx
        - uwsgi
        - graphdb
        - postgres
