version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git 
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.14.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Tests
          command: |
            set -x
            /home/ubuntu/virtualenvs/venv-3.5.3/bin/docker-compose run uwsgi python manage.py makemigrations
            /home/ubuntu/virtualenvs/venv-3.5.3/bin/docker-compose run uwsgi python manage.py test
